Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "rum")
Ingredient.create(name: "vodka")
Ingredient.create(name: "tequila")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "basil")
Ingredient.create(name: "champagne")
Ingredient.create(name: "whisky")
Ingredient.create(name: "cognac")
Ingredient.create(name: "strawberry schnapps")
Ingredient.create(name: "apple juice")
Ingredient.create(name: "apple cider")
Ingredient.create(name: "vermouth")
Ingredient.create(name: "amaretto")
Ingredient.create(name: "cacao")
Ingredient.create(name: "sugar")
Ingredient.create(name: "grapefruit juice")
Ingredient.create(name: "lime")
Ingredient.create(name: "ginger")
Ingredient.create(name: "tomato juice")
Ingredient.create(name: "coffee")
Ingredient.create(name: "creme de cassis")
Ingredient.create(name: "mezcal")
Ingredient.create(name: "milk")
Ingredient.create(name: "cream")
Ingredient.create(name: "passionfruit extract")
Ingredient.create(name: "peach juice")
